

services:
  esbao:
    build:
      context: ./esbao
      dockerfile: Dockerfile
    container_name: esbao-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://dpg-cqk125eehbks73ck503g-a.oregon-postgres.render.com:5432/esbao_db
      - DB_USER_NAME=esbao_db_user
      - DB_PASSWORD=KXdHsokGbqQK5fGdvYurj1s4b5hdekC2
      - DB_JWT_PRIVATE=jwtKeys/private.key.pem
      - DB_JWT_PUBLIC=jwtKeys/public.key.pem
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: esbao-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=esbao_bd
      - POSTGRES_USER=esbao_db_user
      - POSTGRES_PASSWORD=KXdHsokGbqQK5fGdvYurj1s4b5hdekC2
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: